name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get release version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Update manifest version
        run: |
          sed -i 's/"version": "[^"]*"/"version": "${{ steps.get_version.outputs.VERSION }}"/' custom_components/grasplet/manifest.json

      - name: Create release archive
        run: |
          cd custom_components
          zip -r ../grasplet-${{ steps.get_version.outputs.VERSION }}.zip grasplet/

      - name: Upload release archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./grasplet-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: grasplet-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip